name: 拉取kubesphere官方镜像，并推送到私有仓库

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取KubeSphere官方镜像，并推送到私有仓库
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-beijing.aliyuncs.com
        docker build -t registry.cn-beijing.aliyuncs.com/marbleqi/kong:3.0.1 .
        docker push registry.cn-beijing.aliyuncs.com/marbleqi/kong:3.0.1
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
